env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  no-console: 0,
  linebreak-style: 0,
  import/extensions: 0
}
